export const GET_USER_COURSES = "GET_USER_COURSES";
export const GET_USER_COURSE_UNIT = "GET_USER_COURSE_UNIT";
export const GET_CURRENT_UNIT = "GET_CURRENT_UNIT"
export const SET_FINISHED_UNIT = "SET_FINISHED_UNIT"